prompts:
  - type: SimpleText
    instructions: Summarize this content in 4-8 sentences in a style consistent with Youtube video description fields.  What are the main themes?  What are the lessons learned?
    outputfilename: Summary.txt
  - type: SimpleText
    instructions: Create a clickbait-style title for this content based on its main themes.
    outputfilename: Title.txt
  - type: SimpleText
    instructions: If this video were uploaded to youtube, what hashtags would you select to maximize its reach?
    outputfilename: Hashtags.txt
  - type: SimpleText
    instructions: Create a list of discussion questions based on the content for viewers to consider.  The questions should be a bit open-ended and designed for use in a small group or family setting.
    outputfilename: DiscussionQuestions.txt
  - type: SimpleText
    instructions: Impersonate the speaker from this message, using their tone and style, and write an invitation email to invite people to next week's message.
    outputfilename: Invitation.txt
  - type: SimpleText
    instructions: Write a blog post approximately 1200 words long which covers the content of the message.  The goal of this blog post is to provide the same general content but in written form instead of video.  You can use a mild informal style - don't fully mimic the speaker, but imagine how they would write the blog if they were trying to be professional about their writing.
    outputfilename: Blog.txt 
  - type: SimpleText
    instructions: The speaker in this video usually preaches sequentially through a book of the Bible, one chapter per week.  Based on this information, provide an outline of the passage for next week's message, showing main themes and key characters or topics.
    outputfilename: NextWeek.txt
  - type: VideoClipArray
    instructions: Select 5 important quotable moments that we can use for short-form social media content.  Use direct transcript quotations ONLY, do not format or add notes or alter the original text in any way.
    count: 5
    outputfilename: Quotables.txt
    videoclipnamepattern: quote
    videoextension: .mp4
